### PR TITLE
MODIFIED: directory(+Directory) option for archive_create/3

### PR DESCRIPTION
**Pull request by honnix**
This option can be used to simulate -C of tar in order to create
archive in which all paths of files/dirs are relative to Directory.

### CODE REVIEW

**Comment by JanWielemaker** [comment]
Thanks.  Merged after some layout changes.  Also changed the commit message to ADDED:.  The MODIFIED tag is for incompatible changes.

**Comment by honnix** [comment]
OK. Thanks. I thought it was incompatible because the semantics of `directory(+Directory)` changes and also the result is different.

**Comment by JanWielemaker** [comment]
In a sense, that is of course true.  If I'm not mistaken though, it did not process `directory(+Dir)`, so
nothing changes unless you pass this new option.  If you follow the strict line, anything including bug fixes are MODIFIED.  That kind of looses the point to have a tag that is likely to affect applications.
In this case this seems highly unlikely to me, even more so because the entire predicate is so new.

**Comment by honnix** [comment]
OK. That makes perfect sense. Thanks. 

Best regards,
Hongxin

**Pull request closed without merging**
