### PR TITLE
ENHANCED: archive_extract/3 added and enhanced options

### PR DESCRIPTION
**Pull request by erlanger**
Add `include` option, since we already have `exclude`.
The use case is the (unreleased) work in progress to build android apps directly from swi prolog where we need to extract specific shared libraries from an archive.

### CODE REVIEW

**Comment by erlanger** [comment]
Also enhance the `remove_prefix` option to support a list.

**Comment by JanWielemaker** [comment]
Looking forward to the Android app builder!   Merged after some edit.  Also merged the two commits as my edit affected both.   I think the matches `-1` was both confusing and meaningless as the matching clause didn't cut and removing the prefix didn't deal with no such option and the processing needs to
be `det`, which it wasn't.  Blame me and complain if I messed something up.

**Comment by erlanger** [comment]
Thanks! It works fine.
Things are moving forward with the apk builder. 
The major hurdle we will have to work out is that we need to generate 32bit qsave files (for the target android device) on a 64bit host.

**Comment by erlanger** [comment]
In terms of the API I was thinking of a `word_size(S)` option to `qsave_program`.

**Comment by JanWielemaker** [comment]
> Things are moving forward with the apk builder.

Great!  Looking forward!

> The major hurdle we will have to work out is that we need to generate 32bit qsave files (for the target android device) on a 64bit host.

I guess we have two options: the native friend approach or really start a program to make VM code word-size independent.   I do not have a very clear idea where development will first concentrate.  That is under discussion and should materialize in the near future.

The state already has a word-size indication, avoiding loading an incompatible state.

**Comment by erlanger** [comment]
I think the native friend approach works for cross-compiling swi-prolog, but not for the android app builder.
The reason is that people will have to have two swi-prolog installations to call the `build_apk` predicate this will make it difficult to use. It will also require people to install multi-architecture support. 

I think the best way is to find a way to make the VM code word-size independent (since it is already endianness independent).

**Comment by JanWielemaker** [comment]
> I think the best way is to find a way to make the VM code word-size independent (since it is already endianness independent).

I think so too.  I already spent some time getting an idea of the impact.   It is certainly doable, but not in the famous _rainy Sunday afternoon_ (despite we having plenty of those this winter).   The _endianness_ is rather trivial as it just requires some byte swaps.   Now we have operations on objects such as fast integers, which are integers that fit, including tags, in a word.   A 50 bit integer is fast on 64-bit, but a general integer on 32 bits, creating a different instruction with a different size counted in words.  The latter requires recomputing the label addresses.  

There are several ways out.  One is to dynamically translate the VM code.   Another is to abstract the format a little and do the materialization while loading.  The latter will cause some slowdown.  We can possibly compensate for that if we do the materialization lazily as we need the clause.  That way we may even gain performance (at least, reduce the startup time).

**Comment by erlanger** [comment]
hmm...
I think you might be on the verge of an extremely powerful architecture here.
The 'materialization' of the vm code can happen through hooks, something like `term_expansion` but for the VM. If these hooks could be provided in prolog as well as in C, it would open the door for tremendous possibilities in addition to portability. Such as JIT compilation into machine code, based on user hooks (priviledged user of course). It is the power of `term_expansion` at the VM level. Something like `vm_expansion`.

These hooks could be called lazily or not, depending on options. This would be extremely powerful; you may have something very special here which I don't think any other language (except perhaps lisp) is at the point of doing.

**Comment by JanWielemaker** [comment]
We'll see.   Hot-spot optimization is in my mind for a long time.   For now we have a more mundane problem.   I did realize the first step: allow instructions to change size while loading.  That is doable with a less than 1% slowdown loading a state, which seems acceptable.   I think that means that a binary format that is much less machine dependent is in reach.

**Pull request closed without merging**
