### PR TITLE
TEST: Added tests for code snippets in documentation and check_instal…

### PR DESCRIPTION
**Pull request by kamahen**
…lation

  Fixed typos in documentation
  Added tests that cause memory leaks and exercise error conditions / failure

This is related to https://github.com/SWI-Prolog/packages-archive/issues/16

### CODE REVIEW

**Comment by JanWielemaker** [comment]
Tests are of course always nice.    s is, it is not going to work though.   For some platforms where we need to do cross-compilation we test in the installed system (there is a CMAKE option for this).   This means you cannot use the files from the source tree as example data and the use of additional environment variables is also undesirable.   If you need files, I guess picking some files from the installed tree (e.g., the library) is the simplest.

Otherwise it doesn't seem high priority to fix this.

**Comment by kamahen** [comment]
For cross-system testing, is it OK to use the files in the current directory (which by experiment is `/home/peter/src/swipl-devel/build/packages/archive`) or in `../../home/library`? Alternatively, I can easily create some temp files, begin_tests(archive, [setup(...)]),

**Comment by kamahen** [comment]
I've removed the environment variable and changed the tests to use `../../home/library` and `../../packages/archive`. Plus some small changes to the example code (amongst other things, I changed the archive_open, repeat/fail, archive_close to use setup_call_cleanup/3).

**Comment by JanWielemaker** [comment]
Great!  I added a commit that removes most of the assumptions about the build and test environment.   Please pull this before you go on!   That allows for running

    src/swipl ../packages/archive/test_archive.pl
    ?- test_archive.

We should strive to make all tests runable this way as that simplifies running the tests under gdb and in different environments.

**Comment by kamahen** [comment]
I noticed that you removed the two asserta's for user:file_search_path.

For running under ctest, I suppose this is safe (even though `swi('lib/x86_64-linux')` and `swi(lib)` are ahead of `packages/archive` -- but when running from the command line, is it also guaranteed to be safe?

BTW, I noticed that the first result for `foreign` under ctest is a bit surprising: `end_of_file`. I found this by adding an always-fail test and looking at the error message:
```
test(t0, Xs=='') :-
    findall(Path, user:file_search_path(foreign,Path), Xs).
```

**Comment by JanWielemaker** [comment]
> but when running from the command line, is it also guaranteed to be safe?

Yes.   CMake guarantees you can run the executables in the build tree.   home/swipl.rc makes sure all foreign components can be found.

> bit surprising: `end_of_file`

I don't really understand what you are saying.

**Comment by kamahen** [comment]
A big thank-you for improving the code that I wrote!

**Comment by kamahen** [comment]
About the `end_of_file` thing.

I added these tests (which fail and print out the file_search_path and resolution of foreign(archive4pl)) to test_archive.pl:
```
test(t0, FileSearchPaths=='FileSearchPaths') :-
    findall(Path, user:file_search_path(foreign,Path), FileSearchPaths).

test(t1, AbsoluteFileNames=='AbsoluteFileNames') :-
    findall(Path, absolute_file_name(foreign(archive4pl),Path,[file_type(executable),solutions(all)]), AbsoluteFileNames).
```

These produced the following outputs (slightly edited). As you can see, the first result from querying `user:file_search_path/2` is `end_of_file`, which doesn't appear when I run the tests manually.


_FileSearchPaths_
```
[end_of_file,swi('lib/x86_64-linux'),swi(lib),'/home/peter/src/swipl-devel/build.sanitize/packages/pcre', ...]
```

_AbsoluteFileNames_
```
['/home/peter/src/swipl-devel/build.sanitize/packages/archive/end_of_file/archive4pl.so','/home/peter/src/swipl-devel/build.sanitize/packages/archive/end_of_file/archive4pl','/home/peter/src/swipl-devel/build.sanitize/home/lib/x86_64-linux/archive4pl.so','/home/peter/src/swipl-devel/build.sanitize/home/lib/x86_64-linux/archive4pl','/home/peter/src/swipl-devel/build.sanitize/home/lib/archive4pl.so','/home/peter/src/swipl-devel/build.sanitize/home/lib/archive4pl','/home/peter/src/swipl-devel/build.sanitize/packages/pcre/archive4pl.so','/home/peter/src/swipl-devel/build.sanitize/packages/pcre/archive4pl', ...]
```

**Comment by JanWielemaker** [comment]
I see.   Harmless, but probably something fishy is happening.

**Pull request merged**
