### PR TITLE
Added: archive_create/3 to create archive

### PR DESCRIPTION
**Pull request by honnix**
Added predicate archive_create/3 to create archive from a list of
input files or directories with various filters and formats support.

### CODE REVIEW

**Comment by honnix** [comment]
This is my first attempt. Not sure how to use PL_blob_data in this case. So bear with me if I've made some fundamental mistakes. Thanks.

**Comment by honnix** [comment]
Found some problems. I will fix them now.

**Comment by JanWielemaker** [comment]
Sorry for the late response.  Matt Lilley also came with a plan for adding write report, so I pointed him to your work here.   His observation, which I second, is that the interface must be based on Prolog streams instead of files.   Thus, there must be a predicate to open an archive in write mode and one-by-one open new entries in the archive and send data to the archive by writing to a Prolog stream.   This creates a symmetric read/write interface and allows for creating archives from data of diverse sources without creating intermediate files.

A file-based interface as you have added can then be added on top of that.  This layering also avoids all the portability issues with file system interaction.

**Comment by honnix** [comment]
OK. That's more or less what I anticipated. :) I will take a look and think about it. For now, I will close the PR. Thank you very much for the suggestion.

**Comment by thetrime** [comment]
I hope to have this finished this week. The API that honnix proposed is nice and easy to use, so I'll add a predicate in archive.pl that replicates the functionality in my proposed replacement

**Comment by honnix** [comment]
Hi Matt,

Good to know that you have already been working on this and close to finish. I will then stop investigating. I will definitely check out your contribution to learn the right way to play with Prolog stream. Thanks a lot!

Best regards,
Hongxin

**Comment by honnix** [comment]
It's great to know that archive_create/3 has been implemented! Thank you very much. Just a minor comment, the comment of this predicate is not so clear in terms of the behavior and what can be used as option.

And BTW, ChangeLog seems to be broken:

```
Internal server error

directory `'/home/swipl/src/swipl-devel'' does not exist
In:
[22] '$sig_atomic'(git: ...)
[21] setup_call_catcher_cleanup(git: ...,git: ...,_G248,git: ...) at /usr/lib/swi-prolog/boot/init.pl:311
[19] git:git_process_output([log|...],git: ...,[...]) at /usr/lib/swi-prolog/library/git.pl:218
[17] changelog:versions_no_cache('origin/master',_G300) at /home/jan/src/plweb/changelog.pl:184
[16] changelog:versions(development,'origin/master',_G317) at /home/jan/src/plweb/changelog.pl:177
[14] changelog:defaults(_G332,_G333,development) at /home/jan/src/plweb/changelog.pl:59
[13] changelog:changelog([...|...]) at /home/jan/src/plweb/changelog.pl:39
[12] http_dispatch:call_action(changelog:changelog,[...|...]) at /usr/lib/swi-prolog/library/http/http_dispatch.pl:729
[10] time:run_alarm_goal('$alarm'(34945946368152),http_dispatch: ...) at /usr/lib/swi-prolog/library/time.pl:139
[9] setup_call_catcher_cleanup(time: ...,time: ...,_G409,time: ...) at /usr/lib/swi-prolog/boot/init.pl:310
[5] httpd_wrapper:call_handler(http_dispatch: ...,149872,-) at /usr/lib/swi-prolog/library/http/http_wrapper.pl:297
[4] catch(httpd_wrapper: ...,error(...,...),httpd_wrapper:true) at /usr/lib/swi-prolog/boot/init.pl:274
[3] httpd_wrapper:handler_with_output_to(http_dispatch: ...,149872,-,current_output,error(...,...)) at /usr/lib/swi-prolog/library/http/http_wrapper.pl:283
[2] httpd_wrapper:http_wrap_spawned(http_dispatch: ...,_G503,_G504) at /usr/lib/swi-prolog/library/http/http_wrapper.pl:136
[1] thread_httpd:wrap_spawned(<stream>(0x7f21f81d6320),http_dispatch: ...) at /usr/lib/swi-prolog/library/http/thread_httpd.pl:804
[0] <meta call>

SWI-Prolog httpd at swi-prolog.osuosl.org
```

**Comment by JanWielemaker** [comment]
Website ChangeLog fixed.  Please do not mix topics.

**Pull request closed without merging**
