### PR TITLE
ENHANCED: Add archive_foldl/4

### PR DESCRIPTION
**Pull request by erlanger**
Archives are heavily used for the android app builder, this simplifies the work and it is very useful in general.

### CODE REVIEW

**Comment by JanWielemaker** [comment]
I like the idea of a high order predicate for processing archives.   There are some dubious things with the current proposal though.   My main points:

  - The name `for_each` links to `foreach/2`, which is a pretty difficult predicate and precisely
     __not__ a failure driven loop.  Should be `forall`.
  - The implementation does not fail if the goal fails.  This easily leads to incomplete processing
    without signalling the user.

That is easily fixed.  I wonder though whether the `foldl` family is not a better way for processing archives as it facilitates for example getting a list of entries with properties.  E.g., we would get

    archive_foldl(:Goal, +Archive, +State0, -State)

**Comment by erlanger** [comment]
I think the `foldl` idea is great, much better than for_each. This is why I appreciate your "tips" so much.

Edit: Updated the PR.

**Comment by erlanger** [comment]
Okay, here is a try at `archive_foldl/4`. 
I'm not too sure about the `setup_call_cleanup` or the Goal throw/fail behavior.
Let me know what you think.

**Comment by JanWielemaker** [comment]
Better.  I don't really like collecting the properties though.  Then you have them in a list and most likely all you'll do is call a memberchk to get one or two of them.   We also do not know how cheap the computation is for all supported archive formats.  In addition it means an extra argument, which adds
to the confusion (which arguments, what order?)

I'm also in favor of failing if calling the closure fails.  That is much more robust and if the user wants to ignore failures it is easy enough.    Or, do I miss some intended use case?

**Comment by erlanger** [comment]
> Better. I don't really like collecting the properties though.

Yes, I was thinking the same thing after sending the PR.
I think we have two options:

1. The user partially instantiates the Properties argument with the wanted properties
  (like `[file_type(FType), mtime(MTime)]`) and then we instantiate the properties in
  archive_foldl.

2. Only pass the `Handle` and let the user call `archive_header_property`.

I think the first one is more user friendly, but it adds the extra argument.
Which way?

 > I'm also in favor of failing if calling the closure fails. That is much more robust and if the user wants to ignore failures it is easy enough. Or, do I miss some intended use case?

Yes, failing if the closure fails is  better.

**Comment by JanWielemaker** [comment]
>     2\. Only pass the `Handle` and let the user call `archive_header_property`.

That has my preference.   You typically need predicates on the handle anyway.

**Pull request closed without merging**
